runs:
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: openssl-3.0.16
        path: debian/bookworm/libzip/1.11.4/opt/openssl/3.0.16
    - uses: actions/download-artifact@v4
      with:
        name: zlib-1.2.13
        path: debian/bookworm/libzip/1.11.4/opt/zlib/1.2.13
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        context: debian/bookworm/libzip/1.11.4
        outputs: type=local,dest=debian/bookworm/libzip/1.11.4
        platforms: linux/amd64
    - uses: actions/upload-artifact@v4
      with:
        name: libzip-1.11.4
        path: debian/bookworm/libzip/1.11.4/opt/libzip/1.11.4
        retention-days: 8
  using: composite
