runs:
  steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        context: debian/bookworm/icu/77.1.0
        outputs: type=local,dest=debian/bookworm/icu/77.1.0
        platforms: linux/amd64
    - uses: actions/upload-artifact@v4
      with:
        name: icu-77.1.0
        path: debian/bookworm/icu/77.1.0/opt/icu/77.1.0
        retention-days: 8
  using: composite
