runs:
  steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: debian/bookworm/zlib/1.2.13
        outputs: type=local,dest=debian/bookworm/zlib/1.2.13
        platforms: linux/amd64
    - uses: actions/upload-artifact@v4
      with:
        name: zlib-1.2.13
        path: debian/bookworm/zlib/1.2.13/opt/zlib/1.2.13
        retention-days: 8
  using: composite
