runs:
  steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: debian/bookworm/sqlite/3.50.4
        outputs: type=local,dest=debian/bookworm/sqlite/3.50.4
        platforms: linux/amd64
    - uses: actions/upload-artifact@v4
      with:
        name: sqlite-3.50.4
        path: debian/bookworm/sqlite/3.50.4/opt/sqlite/3.50.4
        retention-days: 8
  using: composite
