runs:
  steps:
    - uses: docker/setup-buildx-action@v3
    - uses: actions/cache@v4
      with:
        key: debian-bookworm-brotli-1.1.0-${{ github.run_id }}
        path: debian/bookworm/brotli/1.1.0/cache
        restore-keys: debian-bookworm-brotli-1.1.0
    - uses: docker/build-push-action@v6
      with:
        cache-from: type=local,src=debian/bookworm/brotli/1.1.0/cache
        cache-to: type=local,dest=debian/bookworm/brotli/1.1.0/cache
        context: debian/bookworm/brotli/1.1.0
        outputs: type=local,dest=debian/bookworm/brotli/1.1.0
        platforms: linux/amd64
    - uses: actions/upload-artifact@v4
      with:
        name: brotli-1.1.0
        path: debian/bookworm/brotli/1.1.0/opt/brotli/1.1.0
        retention-days: 1
  using: composite
