runs:
  steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        context: debian/bookworm/zstd/1.5.7
        outputs: type=local,dest=debian/bookworm/zstd/1.5.7
        platforms: linux/amd64
    - uses: actions/upload-artifact@v4
      with:
        name: zstd-1.5.7
        path: debian/bookworm/zstd/1.5.7/opt/zstd/1.5.7
        retention-days: 8
  using: composite
